    - name: Download CNI plugins
      get_url:
        url: "https://github.com/containernetworking/plugins/releases/download/{{ cni_plugins_version }}/cni-plugins-linux-amd64-{{ cni_plugins_version }}.tgz"
        dest: "/tmp/cni-plugins-linux-amd64-{{ cni_plugins_version }}.tgz"

    - name: Create CNI bin directory
      file:
        path: /opt/cni/bin
        state: directory
        mode: '0755'
        recurse: yes

    - name: Extract CNI plugins
      unarchive:
        src: "/tmp/cni-plugins-linux-amd64-{{ cni_plugins_version }}.tgz"
        dest: /opt/cni/bin
        remote_src: yes