--- 
- name: Create sysctl config for IP forwarding
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.ipv4.ip_forward = 1
    mode: '0644'

- name: Apply sysctl settings
  command: sysctl --system

- name: Verify IP forwarding
  command: sysctl net.ipv4.ip_forward
  notify: Update apt cache
