---
# This playbook is built on top of the kubernetes role to install all the kubernetes components and configs.
# Also it deploys all the cluster. 
- name: Install Kubernetes
  hosts: all
  become: yes
  roles: 
    - kubernetes